universe:
  name: nifty_midcap_100_seed
  exchange: NSE
  symbols:
    - ABB.NS
    - ABCAPITAL.NS
    - ABFRL.NS
    - ACC.NS
    - APLAPOLLO.NS
    - ASHOKLEY.NS
    - AUBANK.NS
    - AUROPHARMA.NS
    - BANDHANBNK.NS
    - BANKINDIA.NS
    - BATAINDIA.NS
    - BEL.NS
    - BHARATFORG.NS
    - BHEL.NS
    - BIOCON.NS
    - BOSCHLTD.NS
    - CANBK.NS
    - CGPOWER.NS
    - CHOLAFIN.NS
    - COFORGE.NS
    - COLPAL.NS
    - CONCOR.NS
    - CROMPTON.NS
    - CUMMINSIND.NS
    - DIXON.NS
    - ESCORTS.NS
    - FEDERALBNK.NS
    - GMRINFRA.NS
    - GODREJPROP.NS
    - GUJGASLTD.NS
    - HAL.NS
    - HINDPETRO.NS
    - IDEA.NS
    - IDFCFIRSTB.NS
    - IEX.NS
    - INDHOTEL.NS
    - INDIAMART.NS
    - INDIANB.NS
    - IRCTC.NS
    - JINDALSTEL.NS
    - JSWENERGY.NS
    - LICHSGFIN.NS
    - LTIM.NS
    - LUPIN.NS
    - M&MFIN.NS
    - MANAPPURAM.NS
    - MAXHEALTH.NS
    - MFSL.NS
    - MPHASIS.NS
    - MRPL.NS
    - MUTHOOTFIN.NS
    - NATIONALUM.NS
    - NAUKRI.NS
    - NMDC.NS
    - OBEROIRLTY.NS
    - OFSS.NS
    - PAGEIND.NS
    - PERSISTENT.NS
    - PETRONET.NS
    - PIIND.NS
    - POLYCAB.NS
    - POONAWALLA.NS
    - PRESTIGE.NS
    - RAMCOCEM.NS
    - RECLTD.NS
    - SAIL.NS
    - SHRIRAMFIN.NS
    - SUNTV.NS
    - SYNGENE.NS
    - TATACHEM.NS
    - TATACOMM.NS
    - TATAELXSI.NS
    - TATAPOWER.NS
    - TORNTPOWER.NS
    - TRENT.NS
    - TVSMOTOR.NS
    - UNIONBANK.NS
    - VEDL.NS
    - VOLTAS.NS
    - ZEEL.NS
