ALTER TABLE sector_daily ADD COLUMN IF NOT EXISTS return_1m NUMERIC(8,4);
ALTER TABLE sector_daily ADD COLUMN IF NOT EXISTS return_3m NUMERIC(8,4);
ALTER TABLE sector_daily ADD COLUMN IF NOT EXISTS return_6m NUMERIC(8,4);
ALTER TABLE sector_daily ADD COLUMN IF NOT EXISTS sector_score NUMERIC(8,4);
ALTER TABLE sector_daily ADD COLUMN IF NOT EXISTS sector_rank INTEGER;
