#!/usr/bin/env python3
"""Robustness audit for the 10:30 + VWAP bisection result.

Read-only diagnostic using artifacts generated by audit_entry_vwap_bisection.py.
It checks whether the VWAP improvement is broad or driven by a few trades.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[1]
INPUT_DIR = REPO_ROOT / "reports" / "entry_vwap_bisection"
OUTPUT_DIR = REPO_ROOT / "reports" / "vwap_edge_robustness"
INITIAL_CAPITAL = 1_000_000.0


def pct(value: float | None) -> str:
    if value is None or pd.isna(value):
        return "n/a"
    return f"{value * 100:.2f}%"


def money(value: float | None) -> str:
    if value is None or pd.isna(value):
        return "n/a"
    return f"Rs {value:,.0f}"


def load_trades(period: str, case: str) -> pd.DataFrame:
    path = INPUT_DIR / f"{period}_{case}_trades.csv"
    frame = pd.read_csv(path)
    if frame.empty:
        return frame
    frame["key"] = frame["symbol"].astype(str) + "|" + frame["entry_date"].astype(str)
    return frame


def summarize_concentration(frame: pd.DataFrame) -> dict[str, float | int | None]:
    if frame.empty:
        return {
            "trades": 0,
            "net_pnl": 0.0,
            "top_1_pnl": None,
            "top_3_pnl": None,
            "bottom_1_pnl": None,
            "bottom_3_pnl": None,
            "top_1_share_of_total": None,
            "top_3_share_of_total": None,
        }
    sorted_pnl = frame.sort_values("net_pnl", ascending=False)
    total = float(frame["net_pnl"].sum())
    top_1 = float(sorted_pnl.head(1)["net_pnl"].sum())
    top_3 = float(sorted_pnl.head(3)["net_pnl"].sum())
    bottom_1 = float(sorted_pnl.tail(1)["net_pnl"].sum())
    bottom_3 = float(sorted_pnl.tail(3)["net_pnl"].sum())
    return {
        "trades": int(len(frame)),
        "net_pnl": total,
        "top_1_pnl": top_1,
        "top_3_pnl": top_3,
        "bottom_1_pnl": bottom_1,
        "bottom_3_pnl": bottom_3,
        "top_1_share_of_total": top_1 / total if total else None,
        "top_3_share_of_total": top_3 / total if total else None,
    }


def leave_one_out_stats(frame: pd.DataFrame) -> dict[str, float | str | None]:
    if frame.empty:
        return {}
    total = float(frame["net_pnl"].sum())
    adjusted = frame.copy()
    adjusted["net_pnl_without_trade"] = total - adjusted["net_pnl"]
    adjusted["return_without_trade"] = adjusted["net_pnl_without_trade"] / INITIAL_CAPITAL
    worst_without = adjusted.sort_values("return_without_trade").iloc[0]
    best_without = adjusted.sort_values("return_without_trade").iloc[-1]
    return {
        "total_net_pnl": total,
        "return": total / INITIAL_CAPITAL,
        "worst_leave_one_out_symbol": str(worst_without["symbol"]),
        "worst_leave_one_out_entry": str(worst_without["entry_date"]),
        "worst_leave_one_out_return": float(worst_without["return_without_trade"]),
        "best_leave_one_out_symbol": str(best_without["symbol"]),
        "best_leave_one_out_entry": str(best_without["entry_date"]),
        "best_leave_one_out_return": float(best_without["return_without_trade"]),
    }


def trade_set_delta(no_vwap: pd.DataFrame, with_vwap: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    no_keys = set(no_vwap["key"])
    yes_keys = set(with_vwap["key"])
    removed = no_vwap[no_vwap["key"].isin(no_keys - yes_keys)].copy().sort_values("net_pnl")
    added = with_vwap[with_vwap["key"].isin(yes_keys - no_keys)].copy().sort_values("net_pnl")
    common = no_vwap[no_vwap["key"].isin(no_keys & yes_keys)].copy()
    return removed, added, common


def main() -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    rows = []
    payload: dict[str, object] = {"periods": {}}

    for period in ["FY2024-25", "FY2025-26"]:
        no_vwap = load_trades(period, "entry_1030_no_vwap")
        with_vwap = load_trades(period, "entry_1030_vwap_2p5")
        removed, added, common = trade_set_delta(no_vwap, with_vwap)
        removed.to_csv(OUTPUT_DIR / f"{period}_removed_by_vwap.csv", index=False)
        added.to_csv(OUTPUT_DIR / f"{period}_added_after_vwap_path_change.csv", index=False)

        no_stats = summarize_concentration(no_vwap)
        yes_stats = summarize_concentration(with_vwap)
        no_loo = leave_one_out_stats(no_vwap)
        yes_loo = leave_one_out_stats(with_vwap)
        removed_pnl = float(removed["net_pnl"].sum()) if not removed.empty else 0.0
        added_pnl = float(added["net_pnl"].sum()) if not added.empty else 0.0
        common_no = no_vwap[no_vwap["key"].isin(set(common["key"]))]
        common_yes = with_vwap[with_vwap["key"].isin(set(common["key"]))]
        common_delta = float(common_yes["net_pnl"].sum() - common_no["net_pnl"].sum()) if not common.empty else 0.0
        advantage = float(with_vwap["net_pnl"].sum() - no_vwap["net_pnl"].sum())
        without_best_yes_advantage = advantage - float(with_vwap["net_pnl"].max()) if not with_vwap.empty else None
        without_worst_removed_advantage = advantage - abs(float(removed["net_pnl"].min())) if not removed.empty else None

        row = {
            "period": period,
            "no_vwap_net_pnl": no_stats["net_pnl"],
            "with_vwap_net_pnl": yes_stats["net_pnl"],
            "vwap_advantage_pnl": advantage,
            "vwap_advantage_return": advantage / INITIAL_CAPITAL,
            "removed_trade_count": int(len(removed)),
            "removed_net_pnl": removed_pnl,
            "added_trade_count": int(len(added)),
            "added_net_pnl": added_pnl,
            "common_trade_count": int(len(common)),
            "common_net_pnl_delta": common_delta,
            "with_vwap_top_1_pnl": yes_stats["top_1_pnl"],
            "with_vwap_top_3_pnl": yes_stats["top_3_pnl"],
            "with_vwap_top_1_share_of_net": yes_stats["top_1_share_of_total"],
            "with_vwap_top_3_share_of_net": yes_stats["top_3_share_of_total"],
            "with_vwap_leave_one_out_worst_return": yes_loo.get("worst_leave_one_out_return"),
            "with_vwap_leave_one_out_worst_symbol": yes_loo.get("worst_leave_one_out_symbol"),
            "advantage_after_removing_best_with_vwap_trade": without_best_yes_advantage,
            "advantage_after_removing_worst_removed_trade_effect": without_worst_removed_advantage,
        }
        rows.append(row)
        payload["periods"][period] = {
            "row": row,
            "no_vwap_concentration": no_stats,
            "with_vwap_concentration": yes_stats,
            "no_vwap_leave_one_out": no_loo,
            "with_vwap_leave_one_out": yes_loo,
            "worst_removed": removed.head(5).to_dict(orient="records"),
            "best_added": added.sort_values("net_pnl", ascending=False).head(5).to_dict(orient="records"),
        }

    pd.DataFrame(rows).to_csv(OUTPUT_DIR / "vwap_edge_robustness_summary.csv", index=False)
    (OUTPUT_DIR / "summary.json").write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")

    lines = [
        "# VWAP Edge Robustness",
        "",
        "This read-only diagnostic checks whether the 10:30 + VWAP improvement is broad or driven by a few trades.",
        "",
        "| Period | VWAP Advantage | Removed Trades | Removed PnL | Added Trades | Added PnL | Common PnL Delta | Advantage Ex Best VWAP Trade | Advantage Ex Worst Removed Effect |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        lines.append(
            f"| {row['period']} | {money(row['vwap_advantage_pnl'])} ({pct(row['vwap_advantage_return'])}) | "
            f"{row['removed_trade_count']} | {money(row['removed_net_pnl'])} | {row['added_trade_count']} | {money(row['added_net_pnl'])} | "
            f"{money(row['common_net_pnl_delta'])} | {money(row['advantage_after_removing_best_with_vwap_trade'])} | "
            f"{money(row['advantage_after_removing_worst_removed_trade_effect'])} |"
        )
    lines.extend(["", "## FY2025-26 Worst Trades Removed By VWAP", "", "| Symbol | Entry | Exit | Net PnL | Return |", "| --- | --- | --- | ---: | ---: |"])
    fy25_removed = pd.read_csv(OUTPUT_DIR / "FY2025-26_removed_by_vwap.csv")
    for _, trade in fy25_removed.head(8).iterrows():
        lines.append(f"| {trade['symbol']} | {trade['entry_date']} | {trade['exit_date']} | {money(float(trade['net_pnl']))} | {pct(float(trade['net_return_pct']))} |")
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- If advantage remains positive after removing the best VWAP-case trade, the result is not a single-winner artifact.",
            "- If advantage largely disappears after removing the worst avoided trade effect, the result is materially dependent on avoiding one major loser.",
            "- This is a robustness diagnostic, not a strategy change.",
        ]
    )
    (OUTPUT_DIR / "VWAP_EDGE_ROBUSTNESS.md").write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps(payload, indent=2, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
